'use strict';window.StackExchange={};function CTIsPlayback(){try{return parent&&parent.WebPlayer}catch(f){return!1}}if(!CTIsPlayback()&&top!=self)throw top.location.replace(document.location),$(function(){$("head").add("body").remove()}),alert("For security reasons, framing is not allowed; click OK to remove the frames."),Error();
StackExchange.init=function(){var f=function(a){if(!window.jQuery)if("complete"!=document.readyState)setTimeout(function(){f(a)},1E3);else{var c=document.createElement("div");c.id="noscript-padding";var g=document.createElement("div");g.id="noscript-warning";g.innerHTML=a+" requires external JavaScript from another domain, which is blocked or failed to load.";document.body.insertBefore(c,document.body.firstChild);document.body.appendChild(g)}},a=function(){$(document).keyup(function(a){27==a.which&&
($("#lightbox:not(.no-esc-remove), .error-notification, .popup, .share-tip, .esc-remove").fadeOutAndRemove(),$(".esc-hide").fadeOut(),window.genuwine&&genuwine.isVisible()&&genuwine.click(),window.profileLink&&profileLink.hide())})},d=function(){var a=$("#hlinks"),c=$("#search input[name=q]"),g=c.width(),d=2.5*g,f,j=function(a){c.queue("expand",a)},h=!1,l=!("placeholder"in document.createElement("input"));l&&!StackExchange.options.isMobile&&(""==c[0].value&&(c[0].value="search"),c.bind({focus:function(){"search"==
this.value&&(this.value="")}}));c.keydown(function(g){if(h||46>g.keyCode&&8!=g.keyCode&&32!=g.keyCode)return!0;h=!0;clearTimeout(f);c.clearQueue("expand");j(function(g){c[0].placeholder="";a.fadeOut(100,g)});j(function(a){c.animate({width:d,"max-width":d},100,a)});j(function(){0==c.parent().find(".search-prompt").length&&c.before('<span class="search-prompt">search:</span>')});3==c.queue("expand").length&&c.dequeue("expand")}).focusout(function(){f=setTimeout(function(){j(function(a){c.parent().find(".search-prompt").remove();
a()});j(function(a){c.animate({width:g,"max-width":g},100,a)});j(function(g){l&&""==c[0].value&&(c[0].value="search");c[0].placeholder="search";a.fadeIn(100,g)});3==c.queue("expand").length&&c.dequeue("expand");h=!1},200)});$("#search").keydown(function(a){if(13==a.which&&a.ctrlKey&&c.val())return window.open("/search?q="+encodeURIComponent(c.val()),"_newtab"),!1}).find("input[name=q]").keyup(function(a){27==a.which&&$(this).blur()})};return function(e){StackExchange.options=e;var c=e.serverTime-
(new Date).getTime()/1E3;f(e.site.name);$.ajaxSetup({cache:!1});StackExchange.init.createJqueryExtensions();$(function(){a();d();StackExchange.using(StackExchange.options.user.isAnonymous?"anonymous":"loggedIn",function(){StackExchange.initialized.resolve()},!0,e.fullPostfix);var g=StackExchange.options.styleCodeAdditionalLang;g&&StackExchange.ifUsing("prettify",function(){return StackExchange.loadJsFile("third-party/prettify/additional-langs/"+g)});StackExchange.ready(function(){genuwine.init(e.user.accountId||
null,e.user.inboxUnviewedCount,e.user.notificationsUnviewedCount);e.user.messages&&StackExchange.notify.showMessages(e.user.messages,e.isMobile);e.site.globalAuthDisabled||(!e.site.isChildMeta&&e.user.isAnonymous&&gauth.checkStackAuth(e.stackAuthUrl),gauth.informStackAuth(e.stackAuthUrl));e.user.isAnonymous||profileLink.init(e.user.gravatar,e.isMobile,e.user.profileUrl+"?tab=activity",c);e.enableUserHovercards&&StackExchange.usermenu.init();StackExchange.tagPreferences?StackExchange.tagPreferences.init():
StackExchange.tagmenu.init();$("*[data-tracker]").track()})})}}();
StackExchange.debug={log:function(){},init:function(){this.log=function(f){$(function(){var a=$("#debug-messages");a.length||(a=$("<div id='debug-messages' style='text-align:left;position:fixed;top:50px;left:50px;z-index:1000;background:white;border:2px solid black;width:300px;padding:10px;' />").append($("<span style='cursor:pointer;color:#999'>(close debug messages)</span>").click(function(){$("#debug-messages").remove()})).appendTo("body"));$("<div style='margin-top:10px' />").text(f).appendTo(a)})}}};
StackExchange.initialized=$.Deferred();StackExchange.ready=function(f){StackExchange.initialized.done(f)};if(window.serq)for(var i=0;i<window.serq.length;i++)StackExchange.ready(window.serq[i]);
(function(){var f={anonymous:"full-anon.js",loggedIn:"full.js",prettify:"prettify-full.js",pseudoModerator:"moderator.js",inlineEditing:"full.js",editor:"wmd.js",autocomplete:"third-party/jquery.autocomplete.min.js",tagAutocomplete:"tageditor.js",tagEditor:"tageditornew.js",tagSuggestions:"tagsuggestions.js",mobile:"mobile.js",help:"help.js",inlineTagEditing:"inline-tag-editing.js",mathjaxEditing:"mathjax-editing.js",revisions:"revisions.js",mockups:"mockups.js",review:"review.js",translation:"full.js",
gps:"full-anon.js"},a={},d={},e,c={},g=function(a,g){return function(c){var e=a[c];e||(e=a[c]=g(c));return e}},n=function(g){var g=a[g],c,e=$.Deferred(),d=$.when(e),f;if(g)for(c=0;c<g.length;c++)(f=g[c].call(null))&&$.isFunction(f.promise)&&(d=$.when(d,f));e.resolve();return d},k=function(){if(!e){var a=$("script[src*='/stub.js']:first");0==a.length?(StackExchange.debug.log("couldn't figure out location of stub.js"),e="/content/js/"):e=a.attr("src").replace(/\/stub\.js.*$/,"/")}return e},j=function(a){var g=
$.Deferred(),c=document.createElement("script");c.async="async";c.type="text/javascript";c.src=a;c.onload=c.onreadystatechange=function(a,e){if(!c.readyState||/loaded|complete/.test(c.readyState))e?g.reject():g.resolve()};c.onerror=function(){g.reject()};$("head")[0].appendChild(c);return g.promise()},h=function(a){a=f[a];return!a?$.Deferred().reject().promise():l(a)},l=g({},function(a){var g=k()+a;var e=c["js/"+a];e?a="?v="+e:(StackExchange.debug.log("no cache breaker for "+a),a="");return j(g+a)}),
o=g({},function(a){function g(){(e=StackExchange[a])?n(a).done(function(){c.resolve()}):0<d?(d--,StackExchange.debug.log("retrying "+a),setTimeout(g,20)):(StackExchange.debug.log("object "+a+" not available although file was loaded"),c.reject())}var c=$.Deferred(),e=StackExchange[a],d=3;e?c.resolve():h(a).done(g).fail(c.reject);return c.promise()}),p=$.Deferred(),q=function(a,g,c,e){if(!c&&!p.isResolved())p.done(function(){q(a,g)});else{if(c)for(var d in f)f.hasOwnProperty(d)&&(f[d]=f[d].replace(/^(full(?:-anon)?).js$/,
"$1"+(e||"")+".js"));e=o(a);c?p.resolve():e=$.when(e,StackExchange.initialized);e.done(function(){g()}).fail(function(){StackExchange.debug.log("failed to provide object "+a)});return e}};q.setCacheBreakers=function(a){for(var g in a)a.hasOwnProperty(g)&&(c[g]=a[g])};StackExchange.using=q;StackExchange.ifUsing=function(g,c,e){if("undefined"!==typeof e){if(d["u_"+e])return;d["u_"+e]=!0}StackExchange[g]?c():((e=a[g])||(e=a[g]=[]),e.push(c))};StackExchange.loadJsFile=function(a){return j(k()+a)}})();
String.prototype.format=function(){var f=this.toString();if(!arguments.length)return f;var a="string"==typeof arguments[0]?arguments:arguments[0],d;for(d in a)f=f.replace(RegExp("\\{"+d+"\\}","gi"),a[d]);return f};String.prototype.truncate=function(f,a){var d=this.toString();f&&d.length>f&&(d=d.substr(0,f)+a);return d};String.prototype.splitOnLast=function(f){f=this.lastIndexOf(f);return 0>f?[this]:[this.substr(0,f),this.substr(f)]};String.prototype.contains=function(f){return-1<this.indexOf(f)};
StackExchange.init.createJqueryExtensions=function(){var f=StackExchange.helpers;$.extend($.expr[":"],{working:function(a){a=$(a).data("working");return"undefined"!==typeof a&&a},data:function(a,d,e){d=e[3];a=$(a).data(d);switch(typeof a){case "undefined":return!1;case "boolean":return a;case "object":return null!==a}return!0}});$.fn.extend({working:function(a){return this.each(function(){$(this).data("working",a)})},track:function(){return this.each(function(){var a=$(this),d=a.is("a[href]")?a:a.find("a[href]"),
e=a.data("tracker");d.each(function(){var a=this.href.splitOnLast("#"),g=a[0];this.href=g+=(g.contains("?")?"&":"?")+e+(a[1]||"")})})},fadeOutAndRemove:function(){return this.each(function(){var a=$(this);a.fadeOut("fast",function(){a.trigger("removing").remove()})})},charCounter:function(a){return this.each(function(){var d=a.target?$(a.target):$(this).parents("form").find("span.text-counter"),e=this;$(this).bind("blur focus keyup paste",f.DelayedReaction(function(){var c=a.min,g=a.max,f=a.setIsValid||
function(){},k=e.value?e.value.replace(/\r\n/g,"\n").length:0,j=k>0.8*g?"supernova":k>0.6*g?"hot":k>0.4*g?"warm":"cool",h="";0==k?(h="enter at least "+c+" characters",f(!1)):k<c?(h=c-k+" more to go...",f(!1)):(c=g-k,h=0<=c?c+" character"+(1!=c?"s":"")+" left":"too long by "+Math.abs(c)+" character"+(-1!=c?"s":""),f(k<=g));d.text(h);d.hasClass(j)||d.removeClass("supernova hot warm cool").addClass(j)},100,{sliding:!0}).trigger)})},selectRange:function(a,d){return this.each(function(){if(this.setSelectionRange)this.focus(),
this.setSelectionRange(a,d);else if(this.createTextRange){var e=this.createTextRange();e.collapse(!0);e.moveEnd("character",d);e.moveStart("character",a);e.select()}})},addSpinner:function(a){return this.each(function(){f.addSpinner(this,a)})},addSpinnerAfter:function(a){return this.each(function(){$(this).after(f.getSpinnerImg(a))})},removeSpinner:function(){return this.each(function(){$(this).find("img.ajax-loader").remove()})},showErrorPopup:function(a,d,e){return this.each(function(){f.showErrorPopup(this,
a,d,e)})},center:function(){var a=this.parent();"static"===a.css("position")&&(a=a.offsetParent());var a=a.offset(),d=$(window);this.css("position","absolute");this.css("top",Math.max((d.height()-this.outerHeight())/2+d.scrollTop()-a.top,0)+"px");this.css("left",Math.max(20,(d.width()-this.outerWidth())/2+d.scrollLeft()-a.left)+"px");a="calc(50% - "+this.outerWidth()/2+"px)";this.css("left",a);this.css("left","-webkit-"+a);return this},helpOverlay:function(){f.bindHelpOverlayEvents(this);return this},
hideHelpOverlay:function(){f.hideHelpOverlay(this);return this},enable:function(){0==arguments.length||arguments[0]?this.removeAttr("disabled").css("cursor","pointer").removeClass("disabled-button"):this.attr("disabled","disabled").css("cursor","default").addClass("disabled-button");return this},disable:function(){return this.enable(!1)},loadPopup:function(a){var d=this;d.addSpinnerAfter({padding:"0 3px"});$.ajax({type:"GET",url:a.url,dataType:"html",success:function(e){var c=$(e);c.find(".popup-actions-cancel, .popup-close a").click(function(){c.fadeOutAndRemove();
a.lightbox&&$("#lightbox").fadeOutAndRemove()});c.find("input:radio[disabled=disabled] + label.action-label").addClass("action-disabled");a.hideDescriptions&&c.find("ul.action-list > li:not(.action-selected) .action-desc").hide();e=c.find("input:radio:not(.action-subform input)");e.closest("li").bind("hide-action",function(){var g=$(this),c=".action-subform"+(a.hideDescriptions?", .action-desc":"");g.removeClass("action-selected").find(c).slideUp("fast")}).bind("show-action",function(){var g=$(this);
g.hasClass("action-selected")||(g.siblings(".action-selected").trigger("hide-action"),g.addClass("action-selected").find(".action-subform").slideDown("fast",function(){a.subformShow&&a.subformShow($(this));if(a.subformFocusInput){var g=$(this).find("input[type=text], textarea").not(".actual-edit-overlay").eq(0);g.length&&g.focus()}}),a.hideDescriptions&&g.find(".action-desc").slideDown("fast"),a.actionSelected&&a.actionSelected(g),c.find(".popup-submit").enable())});e.click(function(){$(this).closest("li").trigger("show-action")});
c.appendTo(d.parent());a.loaded&&a.loaded(c);e=function(){};if(a.subformShow){var g=c.find("li.action-selected .action-subform");0<g.length&&(e=function(){g.each(function(){a.subformShow($(this))})})}if(a.lightbox){var f=$('<div id="lightbox"/>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");c.css("z-index",f.css("z-index")+1)}a.dontCenter||c.center().fadeIn("fast",e)},error:function(){d.parent().showErrorPopup("Unable to load popup - please try again")},complete:f.removeSpinner});
return d},asyncLoad:function(){return this.each(function(){var a=$(this),d=a.find(".async-load");a.hasClass(".async-load")&&(d=d.add(a));d.each(function(){var a=$(this),c=a.data("load-url")||"";c&&!a.is(":working")&&(a.working(!0).addSpinner(),$.ajax({type:"GET",url:c,dataType:"html"}).done(function(g){a.html(g).removeClass("async-load").mathjax();if(g=a.data("after-load")||""){for(var g=g.split("."),c,d=0;d<g.length;d++)c=(c||window)[g[d]];"function"===typeof c&&c(a)}}).fail(function(){a.removeSpinner().showErrorPopup("An error has occurred; please try again")}))})})},
mathjax:function(){return this.each(function(){"undefined"!=typeof MathJax&&MathJax.Hub.Typeset(this)})}})};
StackExchange.helpers=function(){function f(a,c,d){for(var f=0;f<d.length;f++){var h=d[f];try{if(/\*/.test(h))for(var l=0;4>l;l++){var o=h.replace(/\*/g,e[l]),p=a.css(o);c.css(o,p)}else c.css(h,a.css(h))}catch(q){}}}function a(a,c,e,d){if(a.is(":visible")){var h=$.browser.msie?0:0.4;e()?(a.css("opacity",h+(d?0.2:0)),a.addClass("edit-field-overlayed"),e=a.prev(".actual-edit-overlay"),0==e.length&&(d=a.parent().find("span.edit-field-overlay").text(),e=a.width(),h=a.height(),e=a.clone().prop("className",
"actual-edit-overlay").attr("name",null).attr("id",null).attr("disabled","disabled").css({position:"absolute",backgroundColor:"white",color:"black","-webkit-text-fill-color":"black",opacity:1,width:e,height:h}),e.is("textarea,input")?(e.val(d),f(c,e,["line-height"])):e.text(d).css("line-height",h+"px").prepend("&nbsp;"),f(c,e,["font-family","font-size","text-align"]),f(a,e,["border-*-style","border-*-color","border-*-width"]),a.css({zIndex:1,position:"relative"}),e.insertBefore(a),d=a.offset().top-
e.offset().top,0!=d&&(c=parseInt(e.css("margin-top")),d=c+d,a.is("textarea")||(d=parseInt(e.prevAll(":visible").eq(0).css("margin-bottom"))+c),e.css("margin-top",d)),a=a.offset().left-e.offset().left,0!=a&&(c=parseInt(e.css("margin-left")),e.css("margin-left",c+a)))):a.css("opacity",1).css("filter","").removeClass("edit-field-overlayed")}}function d(a,c){$(a).find("input[type='submit']").prop("disabled",c)}var e=["left","right","top","bottom"],c={genericBindOverlayEvents:function(g,e,d){StackExchange.options.isMobile||
e.bind("keydown contextmenu",function(){c.hideHelpOverlay(g)}).focus(function(){a(g,e,d,!0)}).on("blur change",function(){a(g,e,d)}).each(function(){a(g,e,d)})},bindHelpOverlayEvents:function(a){a.each(function(){var a=$(this);c.genericBindOverlayEvents(a,a,function(){return""===a.val()})})},hideHelpOverlay:function(a){a.css("opacity",1);a.css("filter","");a.removeClass("edit-field-overlayed")},onClickDraftSave:function(a){$(a).click(function(){var a=this.href;StackExchange.cardiologist.ensureDraftSaved(function(){window.onbeforeunload=
null;window.location.href=a});return!1});return!0},showErrorPopup:function(a,c,e,d){$(".error-notification").remove();var f=$('<div class="error-notification supernovabg"><h2>'+c+"</h2>"+(e?"":'<span class="error-close">(click on this box to dismiss)</span>')+"</div>"),l=function(){f.fadeOutAndRemove();d&&d()};$(a).append(f);f.click(l).fadeIn("fast");setTimeout(l,e?Math.max(2500,40*c.length):3E4)},removeErrorPopup:function(){$(".error-notification").fadeOutAndRemove()},addSpinner:function(a,e){$(a).append(c.getSpinnerImg(e))},
getSpinnerImg:function(a){var c=$('<img class="ajax-loader" src="/content/img/progress-dots.gif" title="loading..." alt="loading..." />');a&&c.css(a);return c},removeSpinner:function(){$("img.ajax-loader").remove()},enableSubmitButton:function(a){d(a,!1)},disableSubmitButton:function(a){d(a,!0)},loadTicks:function(a){var c;c=a?a.find(".edit-block"):$(".edit-block");0==c.find("input[name=i1l]").length&&!c.data("loading-ticks")&&(c.data("loading-ticks",!0),$.ajax({url:"/questions/ticks",cache:!1,success:function(a){c.append("<input type='hidden' name='i1l' value='"+
a+"' />")},complete:function(){c.data("loading-ticks",!1)}}))},showFancyOverlay:function(a){var a=a||{},c=$("#overlay-header"),e=a.message||"",d=$.browser.msie?{background:"#fff",opacity:0}:{};!1!==a.showClose&&(e+='<br><a class="close-overlay">close this message</a>');c.html(e).css(d).animate({opacity:"1",height:"show"},"slow",a.complete).find(".close-overlay").click(function(){c.animate({opacity:"0",height:"hide"},"fast")})},DelayedReaction:function(a,c,e){var e=e||{},d,f,l=e.always,o=function(){d=
null;a.apply(null,f)};return{trigger:function(){f=arguments;l&&l.apply(null,f);d?e.sliding&&(clearTimeout(d),d=setTimeout(o,c)):d=setTimeout(o,c)},cancel:function(){d&&(clearTimeout(d),d=null)}}},fireAndForget:function(a){$.ajax({type:"POST",url:a,async:!0})}};return c}();
function prepareEditor(f){var a=f.postfix||"",d=function(){setTimeout(function(){StackExchange.editor.initIfShown(f)},1)};if(f.onDemand){for(var e="bold-button,italic-button,spacer1,link-button,quote-button,code-button,image-button,spacer2,olist-button,ulist-button,heading-button,hr-button,spacer3,undo-button,redo-button".split(","),c=$('<ul id="wmd-button-row'+a+'" class="wmd-button-row" />').appendTo(".wmd-button-bar"),g=0,n=0;n<e.length;n++){var k=e[n],j=/spacer/.test(k),k=$("<li id='wmd-"+k+a+
"' />").prop("className","wmd-"+(j?"spacer":"button")).css("left",25*n).appendTo(c);$("<span />").css("background-position",g+"px -20px").appendTo(k);j||(g-=20)}var h=!1;$("#wmd-input, #title, #tagnames, #edit-comment, #m-address, #display-name").one("focus click keydown",function(){h||(h=!0,c.addSpinner({"float":"right"}),StackExchange.using("editor",function(){c.remove();f.autoShowMarkdownHelp&&(f.immediatelyShowMarkdownHelp=!0);d()}))})}else StackExchange.using("editor",d)}
StackExchange.switchMobile=function(f,a){$.post("/mobile/"+f,{returnurl:a},function(a){window.location=a})};
jQuery.cookie=function(f,a,d){if("undefined"!=typeof a){d=d||{};null===a&&(a="",d.expires=-1);var e="";if(d.expires&&("number"==typeof d.expires||d.expires.toUTCString))"number"==typeof d.expires?(e=new Date,e.setTime(e.getTime()+864E5*d.expires)):e=d.expires,e="; expires="+e.toUTCString();var c=d.path?"; path="+d.path:"",g=d.domain?"; domain="+d.domain:"",d=d.secure?"; secure":"";document.cookie=[f,"=",encodeURIComponent(a),e,c,g,d].join("")}else{a=null;if(document.cookie&&""!=document.cookie){d=
document.cookie.split(";");for(e=0;e<d.length;e++)if(c=jQuery.trim(d[e]),c.substring(0,f.length+1)==f+"="){a=decodeURIComponent(c.substring(f.length+1));break}}return a}};jQuery.expr[":"].regex=function(f,a,d){var a=d[3].split(","),e=/^(data|css):/,d=a[0].match(e)?a[0].split(":")[0]:"attr",e=a.shift().replace(e,"");return RegExp(a.join("").replace(/^\s+|\s+$/g,""),"ig").test(jQuery(f)[d](e))};
$.extend($.expr[":"],{containsExact:function(f,a,d){return $.trim(f.innerHTML.toLowerCase())===d[3].toLowerCase()},containsExactCase:function(f,a,d){return $.trim(f.innerHTML)===d[3]},containsRegex:function(f,a,d){a=/^\/((?:\\\/|[^\/])+)\/([mig]{0,3})$/.exec(d[3]);return RegExp(a[1],a[2]).test($.trim(f.innerHTML))}});
$.extend({URLEncode:function(f){for(var a="",d=0,f=f.toString(),e=/(^[a-zA-Z0-9_.]*)/;d<f.length;){var c=e.exec(f.substr(d));null!=c&&1<c.length&&""!=c[1]?(a+=c[1],d+=c[1].length):(" "==f[d]?a+="+":(c=f.charCodeAt(d).toString(16),a+="%"+(2>c.length?"0":"")+c.toUpperCase()),d++)}return a},URLDecode:function(f){for(var a,d=/(%[^%]{2})/;null!=(m=d.exec(f))&&1<m.length&&""!=m[1];)b=parseInt(m[1].substr(1),16),a=String.fromCharCode(b),f=f.replace(m[1],a);return f}});
(function(f){f.fn.typeWatch=function(a){function d(a){if("TEXT"==a.type.toUpperCase()||"TEXTAREA"==a.nodeName.toUpperCase()){var d={timer:null,text:f(a).val().toUpperCase(),cb:e.callback,el:a,wait:e.wait};e.highlight&&f(a).focus(function(){this.select()});var n=function(a){var c=d.wait,h=!1;13==a.keyCode&&"TEXT"==this.type.toUpperCase()&&(c=1,h=!0);clearTimeout(d.timer);d.timer=setTimeout(function(){var a=h,c=f(d.el).val();if(c.length>e.captureLength&&c.toUpperCase()!=d.text||a&&c.length>e.captureLength)d.text=
c.toUpperCase(),d.cb(c)},c)};f(a).keydown(n).bind("paste",null,function(a){a.which||n(this)})}}var e=f.extend({wait:750,callback:function(){},highlight:!0,captureLength:2},a);return this.each(function(){d(this)})}})(jQuery);
(function(f){function a(a){var c;return a&&a.constructor==Array&&3==a.length?a:(c=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(c[1]),parseInt(c[2]),parseInt(c[3])]:(c=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(c[1]),2.55*parseFloat(c[2]),2.55*parseFloat(c[3])]:(c=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(c[1],16),parseInt(c[2],16),parseInt(c[3],16)]:
(c=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(c[1]+c[1],16),parseInt(c[2]+c[2],16),parseInt(c[3]+c[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?d.transparent:d[f.trim(a).toLowerCase()]}f.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(d,c){f.fx.step[c]=function(d){if(!d.colorInit){var e;e=d.elem;var k=c,j;do{j=f.curCSS(e,k);if(""!=j&&"transparent"!=j||f.nodeName(e,"body"))break;k="backgroundColor"}while(e=e.parentNode);
e=a(j);d.start=e;d.end=a(d.end);d.colorInit=!0}d.elem.style[c]="rgb("+[Math.max(Math.min(parseInt(d.pos*(d.end[0]-d.start[0])+d.start[0]),255),0),Math.max(Math.min(parseInt(d.pos*(d.end[1]-d.start[1])+d.start[1]),255),0),Math.max(Math.min(parseInt(d.pos*(d.end[2]-d.start[2])+d.start[2]),255),0)].join()+")"}});var d={transparent:[255,255,255]}})(jQuery);StackExchange.gps=function(){StackExchange._gps_track=[];return{track:function(f,a){a=a||{};StackExchange._gps_track.push({evt:f,properties:a,now:(new Date).getTime()})}}}();
