define("app/ui/permalink_keyboard_support",["module","require","exports","core/component","app/ui/with_tweet_actions","app/ui/with_focus_highlight"],function(module, require, exports) {
function permalinkKeyboard(){this.defaultAttrs({permalinkTweetSelector:"div.permalink-tweet-container",blockSelector:".block-text",unblockSelector:".unblock-text"}),this.triggerFavorite=function(){this.select("permalinkTweetSelector").find(this.attr.favoriteSelector).first().trigger("click")},this.triggerReply=function(){this.select("permalinkTweetSelector").find(this.attr.replySelector).first().trigger("click")},this.triggerRetweet=function(){this.select("permalinkTweetSelector").find(this.attr.retweetSelector).first().trigger("click")},this.triggerBlock=function(){this.select("permalinkTweetSelector").find(this.attr.blockSelector).first().trigger("click")},this.triggerUnblock=function(){this.select("permalinkTweetSelector").find(this.attr.unblockSelector).first().trigger("click")},this.after("initialize",function(){this.on(document,"uiShortcutFavorite",this.triggerFavorite),this.on(document,"uiShortcutReply",this.triggerReply),this.on(document,"uiShortcutRetweet",this.triggerRetweet),this.on(document,"uiShortcutBlock",this.triggerBlock),this.on(document,"uiShortcutUnblock",this.triggerUnblock)})}var defineComponent=require("core/component"),withTweetActions=require("app/ui/with_tweet_actions"),withFocusHighlight=require("app/ui/with_focus_highlight");module.exports=defineComponent(permalinkKeyboard,withTweetActions,withFocusHighlight)
});
define("app/ui/hidden_ancestors",["module","require","exports","core/component","app/utils/chrome"],function(module, require, exports) {
function hiddenAncestors(){this.defaultAttrs({ancestorAdjustmentClass:"multiple-ancestors-adjustment",amtToShowFromBtmOfFrstNonImdiateAncstr:10,bodySelector:"body",pageContainerSelector:"#page-container",ancestorsWindowContainerSelector:".ancestors-window-container",ancestorsWindowSelector:".ancestors-window",tweetsSelector:".tweets-wrapper .tweet",streamTopSelector:".stream-top"}),this.showHiddenAncestors=function(){if(this.$tweets.length<=1)return;$(this.attr.bodySelector).removeClass(this.attr.ancestorAdjustmentClass);var a=this.select("ancestorsWindowSelector").html();this.select("ancestorsWindowContainerSelector").replaceWith(a),this.select("streamTopSelector").show();var b=chrome.getCanvasYOffset(this.$tweets.last())-1,c=b-$(document).height()+this.$window.height();$(this.attr.pageContainerSelector).css("padding-bottom",c),this.$window.scrollTop(b-this.attr.amtToShowFromBtmOfFrstNonImdiateAncstr)},this.after("initialize",function(){this.$tweets=this.select("tweetsSelector"),this.$window=$(window),this.on(document,"uiPageChanged uiSwiftLoaded",this.showHiddenAncestors)})}var defineComponent=require("core/component"),chrome=require("app/utils/chrome");module.exports=defineComponent(hiddenAncestors)
});
define("app/ui/hidden_descendants",["module","require","exports","core/component"],function(module, require, exports) {
function hiddenDescendants(){this.defaultAttrs({repliesSelector:".replies-to .stream-items .tweet",hasRepliesClass:"has-replies"}),this.updateRepliesState=function(){var a=this.select("repliesSelector");a.length?this.$node.addClass(this.attr.hasRepliesClass):this.$node.removeClass(this.attr.hasRepliesClass)},this.after("initialize",function(){this.on(document,"uiTweetInserted uiTweetRemoved",this.updateRepliesState)})}var defineComponent=require("core/component");module.exports=defineComponent(hiddenDescendants)
});
define("app/ui/dialogs/sms_codes",["module","require","exports","core/component","app/ui/with_position","app/ui/with_dialog"],function(module, require, exports) {
function smsCodesDialog(){this.defaultAttrs({dialogSelector:"#sms-codes-dialog",triggerSelector:".sms-codes-link"}),this.after("initialize",function(a){this.$dialog=this.select("dialogSelector")})}var defineComponent=require("core/component"),withPosition=require("app/ui/with_position"),withDialog=require("app/ui/with_dialog"),SMSCodesDialog=defineComponent(smsCodesDialog,withDialog,withPosition);module.exports=SMSCodesDialog
});
define("app/ui/timelines/conversations/descendant_timeline",["module","require","exports","core/component","app/ui/timelines/with_base_timeline","app/ui/timelines/with_old_items","app/ui/timelines/with_cursor_pagination","app/ui/with_tweet_actions","app/ui/with_item_actions","app/utils/string"],function(module, require, exports) {
function descendantTimeline(){this.defaultAttrs({itemType:"tweet",tweetSelector:".tweet",hiddenRepliesContainerSelector:".hidden-replies-container"}),this.injectOwnReply=function(a,b){if(this.attr.tweetId!==b.in_reply_to_status_id)return;(this.reachedTheEnd()?this.$repliesContainer:this.$hiddenRepliesContainer).append(b.tweet_html),this.$node.removeClass("hidden"),this.trigger("uiTweetInserted",b)},this.restoreHiddenReplies=function(a,b){this.$hiddenRepliesContainer.children().each(function(a,b){var c=$(b),d=c.find(this.attr.tweetSelector).attr("data-tweet-id");this.$repliesContainer.children().each(function(a,b){var e=$(b),f=e.find(this.attr.tweetSelector).attr("data-tweet-id"),g=stringUtils.compare(d,f);if(g===0)return c.remove(),!1;if(g<0)return c.insertBefore(e),!1}.bind(this))}.bind(this)),this.reachedTheEnd()&&(this.$repliesContainer.append(this.$hiddenRepliesContainer.html()),this.$hiddenRepliesContainer.html(""))},this.reachedTheEnd=function(){return!this.select("timelineEndSelector").hasClass("has-more-items")},this.after("initialize",function(a){this.$repliesContainer=this.select("itemsSelector"),this.$hiddenRepliesContainer=this.select("hiddenRepliesContainerSelector"),this.on(document,"dataTweetSuccess",this.injectOwnReply),this.on("uiHasInjectedOldTimelineItems",this.restoreHiddenReplies)})}var defineComponent=require("core/component"),withBaseTimeline=require("app/ui/timelines/with_base_timeline"),withOldItems=require("app/ui/timelines/with_old_items"),withCursorPagination=require("app/ui/timelines/with_cursor_pagination"),withTweetActions=require("app/ui/with_tweet_actions"),withItemActions=require("app/ui/with_item_actions"),stringUtils=require("app/utils/string");module.exports=defineComponent(descendantTimeline,withBaseTimeline,withOldItems,withCursorPagination,withTweetActions,withItemActions)
});
define("app/ui/timelines/conversations/ancestor_timeline",["module","require","exports","core/component","app/ui/timelines/with_base_timeline","app/ui/timelines/with_old_items","app/ui/timelines/with_cursor_pagination","app/ui/with_tweet_actions","app/ui/with_item_actions"],function(module, require, exports) {
function ancestorTimeline(){this.defaultAttrs({itemType:"tweet",isBackward:!0})}var defineComponent=require("core/component"),withBaseTimeline=require("app/ui/timelines/with_base_timeline"),withOldItems=require("app/ui/timelines/with_old_items"),withCursorPagination=require("app/ui/timelines/with_cursor_pagination"),withTweetActions=require("app/ui/with_tweet_actions"),withItemActions=require("app/ui/with_item_actions");module.exports=defineComponent(ancestorTimeline,withBaseTimeline,withOldItems,withCursorPagination,withTweetActions,withItemActions)
});
define("app/data/permalink_scribe",["module","require","exports","core/component","app/data/with_interaction_data_scribe","app/data/with_card_metadata"],function(module, require, exports) {
function permalinkScribe(){this.defaultAttrs({permalinkTweetSelector:".permalink-tweet"}),this.scribePermalinkImpression=function(){var a=this.select("permalinkTweetSelector"),b=this.getCardDataFromTweet(a);b.tweetHasCard&&this.scribeCardInteraction("show",b)},this.after("initialize",function(){this.scribePermalinkImpression()})}var defineComponent=require("core/component"),withInteractionDataScribe=require("app/data/with_interaction_data_scribe"),withCardMetadata=require("app/data/with_card_metadata");module.exports=defineComponent(permalinkScribe,withInteractionDataScribe,withCardMetadata)
});
define("app/pages/permalink",["module","require","exports","app/ui/permalink_keyboard_support","app/ui/dialogs/embed_tweet","app/ui/hidden_ancestors","app/ui/hidden_descendants","app/ui/dialogs/sms_codes","app/ui/timelines/conversations/descendant_timeline","app/ui/timelines/conversations/ancestor_timeline","app/boot/logged_out","app/ui/tweet_injector","app/boot/timeline","app/boot/tweets","app/ui/tweet_box","app/ui/tweets","core/utils","app/boot/app","app/ui/dialogs/uz_survey","app/data/permalink_scribe"],function(module, require, exports) {
var PermalinkKeyboardSupport=require("app/ui/permalink_keyboard_support"),EmbedTweetDialog=require("app/ui/dialogs/embed_tweet"),HiddenAncestors=require("app/ui/hidden_ancestors"),HiddenDescendants=require("app/ui/hidden_descendants"),SMSCodesDialog=require("app/ui/dialogs/sms_codes"),DescendantTimeline=require("app/ui/timelines/conversations/descendant_timeline"),AncestorTimeline=require("app/ui/timelines/conversations/ancestor_timeline"),loggedOutBoot=require("app/boot/logged_out"),TweetInjector=require("app/ui/tweet_injector"),timelineBoot=require("app/boot/timeline"),tweetsBoot=require("app/boot/tweets"),TweetBox=require("app/ui/tweet_box"),Tweets=require("app/ui/tweets"),utils=require("core/utils"),bootApp=require("app/boot/app"),uzSurvey=require("app/ui/dialogs/uz_survey"),PermalinkScribe=require("app/data/permalink_scribe"),permalinkSelector="#page-container.wrapper-permalink",permalinkTweetContainerSelector="div.permalink-tweet-container",permalinkTweetSelector="div.permalink-tweet";module.exports=function(a){function b(b){return utils.merge(a,{eventData:{scribeContext:{component:b}},itemType:"tweet",lastItemSelector:".tweet:last"})}bootApp(a),loggedOutBoot(a),uzSurvey.attachTo("#uz_logged_out_permalink_survey"),tweetsBoot(permalinkSelector,utils.merge(a,{preexpandedTweetSelector:permalinkTweetSelector,preexpandedOpenTweetSelector:permalinkTweetSelector,generalTweetSelector:permalinkTweetSelector})),PermalinkKeyboardSupport.attachTo(document),PermalinkScribe.attachTo(document);var c,d;a.loggedIn?(timelineBoot(a),c=DescendantTimeline,d=AncestorTimeline):c=d=Tweets,HiddenAncestors.attachTo("div.in-reply-to",a),HiddenDescendants.attachTo(".permalink"),Tweets.attachTo(permalinkTweetContainerSelector,b("tweet")),d.attachTo("div.in-reply-to",b("conversation")),c.attachTo("div.replies-to",b("replies")),a.loggedIn?($(permalinkSelector).find(".inline-reply-tweetbox .tweet-form").trigger("uiInitTweetbox",{condensable:!0,preventTweetingDefaultText:!1,inReplyToStatusId:a.tweetId,impressionId:a.impressionId,eventData:{scribeContext:{component:"inline_reply"}}}),a.loggedIn||TweetInjector.attachTo("div.replies-to",{guard:function(b){return b.in_reply_to_status_id==a.tweetId},tweetsSelector:".stream-items"})):SMSCodesDialog.attachTo("body"),a.includeEmbedLink&&EmbedTweetDialog.attachTo(permalinkSelector,{tweetSelector:permalinkTweetSelector,embedData:a.embedData})}
});
define("app/pages/permalink_photo",["module","require","exports","app/ui/permalink_keyboard_support","app/ui/tweets","core/utils","app/boot/app"],function(module, require, exports) {
var PermalinkKeyboardSupport=require("app/ui/permalink_keyboard_support"),Tweets=require("app/ui/tweets"),utils=require("core/utils"),bootApp=require("app/boot/app");module.exports=function(a){bootApp(a),Tweets.attachTo(".media-gallery-overlay",utils.merge({itemType:"tweet",tweetItemSelector:"div.slideshow-tweet",eventData:{scribeContext:{component:"big_photo_permalink"}}},a)),PermalinkKeyboardSupport.attachTo(document,utils.merge({itemType:"tweet"},a))}
});